runtime: go
api_version: go1
threadsafe: true

handlers:
- url: /\.well-known/acme-challenge/(.+)
  static_files: letsencrypt/\1
  upload: letsencrypt/(.+)
  mime_type: text/plain

- url: /.*
  script: _go_app
  secure: always

skip_files:
- ^(.*/)?app\.yaml$
- ^(.*/)?config\.yaml$
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?\..*$
- ^(.*/)?README\.md$
- ^(.*/)?LICENSE$
- ^(.*/)?content\/.*$
- ^(.*/)?data\/.*$
- ^(.*/)?static\/.*$
- ^(.*/)?src\/.*$
- ^(.*/)?node_modules\/.*$
- ^(.*/)?layouts\/.*$
- ^(.*/)?\.git\/.*$
- ^(.*/)?\.gitignore$
