baseurl = "https://quizzical-davinci-efa3b8.netlify.com/"
languageCode = "ja"
title = "Orangesys Inc."
theme = "serviceSite"
metadataformat = "yaml"
canonifyurls = true
pygmentsCodeFences = true

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "orangesys Inc."
	description = "Orangesys - OpenSaaS monitoring"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/orangesys"

	version = "0.1.0"
	logo = "images/common/logo.png"

	permalink = "#"

	# Custom assets
	custom_css  = [
	  "stylesheets/dropdown.css"
	]
	custom_js   = [
	  "javascripts/lunr.min.js",
	  "javascripts/version.js"
	]

	custom_menu = [
    "API"
  ]

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "pink"
    	accent  = "pink"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"
