container_config: &container_config
  docker:
    - image: node:6.9.1
  working_directory: ~/app

workspace_root: &workspace_root
  /tmp/workspace

attach_workspace: &attach_workspace
  attach_workspace:
    at: *workspace_root

load_code: &load_code
  run:
    name: load code from workspace
    command: |
      # Move all files and dotfiles to current directory
      if [ -d "/tmp/workspace/app/" ]; then
        mv /tmp/workspace/app/* /tmp/workspace/app/.[!.]* .
      fi

js_cache_key: &js_cache_key
  key: dependency-npm-v1-{{ checksum "yarn.lock" }}

version: 2.0

jobs:
  build_theme:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          <<: *js_cache_key
      - run:
          name: download dependencies
          command: |
            if [ ! -d node_modules ]; then
              set -exu
              yarn --pure-lockfile --no-progress
            fi
      - save_cache:
          <<: *js_cache_key
          paths:
            - node_modules
      - run:
          name: test orangesys.io
          command: |
            export PATH="$(npm bin):$PATH"
            gulp build:theme
      - run:
          command: |
            mkdir -p /tmp/workspace/app
            mv * .[!.]* /tmp/workspace/app/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - app

  build_content:
    <<: *container_config
    docker:
      - image: cibuilds/hugo:0.30
    steps:
      - *attach_workspace
      - *load_code
      - run:
          name: Show hugo version
          command: hugo version
      - run:
          name: Run hugo
          command: hugo
      - run:
          command: |
            mkdir -p /tmp/workspace/app
            mv * .[!.]* /tmp/workspace/app/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - app          

  deploy:
    <<: *container_config
    docker:
      - image: google/cloud-sdk
        environment:
          GCE_PROJECT: saas-orangesys-io
    steps:
      - *attach_workspace
      - *load_code
      - run:
          name: Deploy to Google App Engine
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode -i > ${HOME}/account-auth.json
            gcloud auth activate-service-account --key-file ${HOME}/account-auth.json
            gcloud -q config set project $GCE_PROJECT
            gcloud -q app deploy app.yaml --promote --version=${CIRCLE_SHA1:0:7}
            curl -s -S -X POST --data-urlencode "payload={'channel': '#ops', 'text': ':earth_asia: :fire: release $CIRCLE_PROJECT_REPONAME (SHA1 ${CIRCLE_SHA1:0:7} completed (build $CIRCLE_BUILD_NUM)' }" $SLACK_OPS >/dev/null
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_theme
      - build_content:
          requires:
            - build_theme
      - deploy:
          requires:
            - build_content
          filters:
            branches:
              only: release
