version: 2.0

references:
  container_config: &container_config
    docker:
      - image: node:8.4.0
        environment:
          PROJECT_NAME: orangesys
          CLOUDSDK_COMPUTE_ZONE: asia-east1-c
          CLUSTER_NAME: orangesysio
    working_directory: ~/app

  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  load_code: &load_code
    run:
      name: load code from workspace
      command: |
        # Move all files and dotfiles to current directory
        if [ -d "/tmp/workspace/app/" ]; then
          mv /tmp/workspace/app/* /tmp/workspace/app/.[!.]* .
        fi

  js_cache_key: &js_cache_key
    key: dependency-npm-{{ checksum "yarn.lock" }}

jobs:
  build_theme:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          <<: *js_cache_key
      - run:
          name: download dependencies
          command: |
            if [ ! -d node_modules ]; then
              set -exu
              yarn --pure-lockfile --no-progress
            fi
      - save_cache:
          <<: *js_cache_key
          paths:
            - node_modules
      - run:
          name: test orangesys.io
          command: |
            export PATH="$(npm bin):$PATH"
            gulp build:theme
      - run:
          command: |
            mkdir -p /tmp/workspace/app
            mv * .[!.]* /tmp/workspace/app/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - app

  build_content:
    <<: *container_config
    docker:
      - image: cibuilds/hugo:0.29
    steps:
      - run:
          name: Run hugo
          command: hugo

  deploy:
    <<: *container_config
    steps:
      - *attach_workspace
      - *load_code
      - run:
          name: build with production
          command: |
            export PATH="$(npm bin):$PATH"
            echo $NODEJS_ENV_PROD | base64 --decode -i > .env
            env $(cat .env | xargs) webpack -p --progress
            firebase deploy --project "$FIREBASE_PROJECT" --token "$FIREBASE_TOKEN" --non-interactive
            curl -s -S -X POST --data-urlencode "payload={'channel': '#ops', 'text': ':earth_asia: :fire: release $CIRCLE_PROJECT_REPONAME (SHA1 $SHORT_HASH) completed (build $CIRCLE_BUILD_NUM)' }" $SLACK_OPS >/dev/null

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_theme
      - build_content:
          requires:
            - build_theme
      - deploy:
          requires:
            - build_content
          filters:
            branches:
              only: release
