version: 2.0
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run:
          name: "Run hugo"
          command: hugo
      # - run:
      #     name: "test website"
      #     command: htmlproofer public --allow-has-href --check-html --empty-alt-ignore --disable-external

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - release
